package day11_0801;



class Demo2{
	int div(int a,int b){
		return a/b;
	}
}


public class ExceptionDemo3 {
	public static void main(String[] args) {
		Demo2 d=new Demo2();
		
		/*法2*/	try{
					int num=d.div(4,0);
					System.out.println("num="+num);
				}
		/*法2*/	catch(Exception e){   
					//处理这个对象，可以使用该对象的方法。
					System.out.println("异常了");  //方法2：捕获异常
					System.out.println(e.getMessage()); //异常信息
					System.out.println(e.toString());   //异常名称+异常信息
					//e.printStackTrace();                //名字+信息+位置 jvm默认用这个处理方式
				}
				
				
				
				
				
				System.out.println("over");

	}

}
